#!/usr/bin/env python3
"""ScratchV: Library-free ONNX → LLVM IR CNN code generator.

Generates human-readable LLVM IR (.ll) with real nested-loop computation
for Conv2D, Gemm, MaxPool, ReLU, Sigmoid, and Reshape operators.

Reuses the ONNX parser (ONNXModel, TensorInfo, NodeInfo, MemoryPlan) from
``onnx_to_riscv_standalone.py`` but emits float32 LLVM IR instead of
Q16.16 RISC-V machine code.

Usage::

    python onnx_to_llvm_standalone.py model.onnx -o output.ll
    python onnx_to_llvm_standalone.py model.onnx --run
"""

from __future__ import annotations

import argparse
import ctypes
import math
import struct
import sys
import time
from typing import Optional

from scratchv.standalone.onnx_to_riscv_standalone import (
    ONNXModel, TensorInfo, NodeInfo, MemoryPlan, ONNX_FLOAT,
)

# ---------------------------------------------------------------------------
# Part 1: LLVMIRBuilder — LLVM IR text emission helper
# ---------------------------------------------------------------------------


class LLVMIRBuilder:
    """Helper for emitting human-readable LLVM IR text.

    Manages SSA register naming, block labels, indentation, and provides
    typed emission methods for float32 compute operations, memory access
    (alloca/load/store/GEP), and control flow (br/br_cond/ret).
    """

    def __init__(self):
        self._lines: list[str] = []
        self._indent = 0
        self._reg_counter = 0
        self._block_counter = 0

    # -- naming ------------------------------------------------------------

    def fresh(self, hint: str = "r") -> str:
        """Return a fresh SSA register name like ``%r_42`` or ``%acc_7``."""
        safe = hint.replace(".", "_").replace("-", "_").replace("/", "_")
        self._reg_counter += 1
        return f"%{safe}_{self._reg_counter}"

    def fresh_block(self, hint: str = "block") -> str:
        """Return a fresh basic-block label name (no ``%`` prefix)."""
        safe = hint.replace(".", "_").replace("-", "_")
        self._block_counter += 1
        return f"{safe}_{self._block_counter}"

    def _p(self, text: str = "") -> None:
        indent = "  " * self._indent
        self._lines.append(f"{indent}{text}")

    # -- formatting helpers ------------------------------------------------

    @staticmethod
    def _float_to_llvm_hex(value: float) -> str:
        """Convert a Python float to LLVM hex float literal (safe for LLVM 20).

        Round-trips through float32 first, then encodes as IEEE 754
        double-precision hex.  This guarantees the value fits in float32.
        """
        # Round-trip through float32 to ensure representability
        f32_bytes = struct.pack("<f", value)
        f32_val = struct.unpack("<f", f32_bytes)[0]
        d = float(f32_val)
        bits = struct.unpack("<Q", struct.pack("<d", d))[0]
        return f"0x{bits:016X}"

    @staticmethod
    def _float_literal(value: float) -> str:
        """Convert a Python float to an LLVM float literal."""
        if value == 0.0:
            return "0.0"
        if value == 1.0:
            return "1.0"
        if value == -1.0:
            return "-1.0"
        return LLVMIRBuilder._float_to_llvm_hex(value)

    @staticmethod
    def _float_dec(value: float) -> str:
        """Format a float for LLVM IR — inline constant."""
        if value == 0.0:
            return "0.0"
        if value == 1.0:
            return "1.0"
        if value == -1.0:
            return "-1.0"
        return LLVMIRBuilder._float_to_llvm_hex(value)

    # -- module level ------------------------------------------------------

    def comment(self, text: str) -> None:
        self._p(f"; {text}")

    def blank(self) -> None:
        self._p("")

    def label(self, name: str) -> None:
        # Labels at column 0, no indent
        indent_bak = self._indent
        self._indent = 0
        self._p(f"{name}:")
        self._indent = indent_bak

    def emit_module_header(self, target_triple: str = "x86_64-unknown-linux-gnu") -> None:
        self.comment("LLVM IR generated by ScratchV — standalone ONNX→LLVM pipeline")
        self.comment('ModuleID = "scratchv_cnn_module"')
        self._p(f'target triple = "{target_triple}"')
        self.blank()

    def emit_declare(self, ret_ty: str, name: str, param_types: list[str]) -> None:
        pts = ", ".join(param_types)
        self._p(f"declare {ret_ty} @{name}({pts})")
        self.blank()

    def emit_global_float_array(self, name: str, values: list[float]) -> str:
        """Emit a constant global float array and return its LLVM name.

        Returns the global name including ``@`` prefix, e.g. ``@w_conv1``.
        """
        global_name = f"@{name}"
        n = len(values)
        self.comment(f"weight: {name}  [{n} x float]")
        # Build comma-separated list, max 8 values per line
        val_lines = []
        current_line_vals = []
        for v in values:
            current_line_vals.append(f"float {self._float_literal(v)}")
            if len(current_line_vals) == 8:
                val_lines.append("  " + ", ".join(current_line_vals))
                current_line_vals = []
        if current_line_vals:
            val_lines.append("  " + ", ".join(current_line_vals))
        val_str = ",\n".join(val_lines)
        self._p(f"{global_name} = private constant [{n} x float] [")
        self._indent += 1
        self._lines.append(val_str)
        self._indent -= 1
        self._p("]")
        self.blank()
        return global_name

    # -- function definition -----------------------------------------------

    def emit_function_start(self, ret_ty: str, name: str,
                            params: list[tuple[str, str]],
                            linkage: str = "",
                            fn_attrs: str = "") -> None:
        """Start a function definition.

        Args:
            ret_ty: Return type, e.g. ``"void"`` or ``"float"``.
            name: Function name (without ``@``).
            params: List of ``(type, name)`` tuples, e.g.
                    ``[("float*", "%input"), ("i32", "%n")]``.
            linkage: Linkage type, e.g. ``"internal"``.
                     Placed between ``define`` and return type.
            fn_attrs: Function attributes, e.g. ``"alwaysinline"``.
                      Placed between param-list and ``{``.
        """
        param_strs = [f"{ty} {nm}" for ty, nm in params]
        linkage_str = f"{linkage} " if linkage else ""
        attrs_str = f" {fn_attrs}" if fn_attrs else ""
        self._p(f"define {linkage_str}{ret_ty} @{name}({', '.join(param_strs)}){attrs_str} {{")
        self._indent += 1

    def emit_function_end(self) -> None:
        self._indent -= 1
        self._p("}")
        self.blank()

    # -- memory ------------------------------------------------------------

    def emit_alloca(self, ty: str, num: int) -> str:
        """Allocate stack space. Returns SSA name of the pointer."""
        r = self.fresh("aptr")
        self._p(f"  {r} = alloca {ty}, i32 {num}")
        return r

    def emit_load(self, ty: str, ptr: str) -> str:
        """Load a value from memory. Returns SSA name of the loaded value."""
        r = self.fresh("ld")
        self._p(f"  {r} = load {ty}, {ty}* {ptr}")
        return r

    def emit_store(self, ty: str, value: str, ptr: str) -> None:
        """Store a value to memory."""
        self._p(f"  store {ty} {value}, {ty}* {ptr}")

    def emit_gep(self, base_ty: str, ptr: str, index: str) -> str:
        """Single-index GEP on a pointer: ``getelementptr ty, ty* ptr, i32 index``."""
        r = self.fresh("gep")
        self._p(f"  {r} = getelementptr {base_ty}, {base_ty}* {ptr}, i32 {index}")
        return r

    def emit_gep_raw(self, result_ty: str, ptr: str, indices: list[str]) -> str:
        """Multi-index GEP with full type annotation.

        For global arrays: emit_gep_raw("[N x float]", "@w", ["i32 0", "i32 idx"])
        """
        r = self.fresh("gep")
        idx_str = ", ".join(indices)
        self._p(f"  {r} = getelementptr {result_ty}, {result_ty}* {ptr}, {idx_str}")
        return r

    # -- float arithmetic --------------------------------------------------

    def emit_float_const(self, value: float) -> str:
        """Materialize a float constant. Returns SSA name."""
        r = self.fresh("fc")
        self._p(f"  {r} = fadd float 0.0, {self._float_dec(value)}")
        return r

    def emit_fadd(self, lhs: str, rhs: str) -> str:
        r = self.fresh("fa")
        self._p(f"  {r} = fadd float {lhs}, {rhs}")
        return r

    def emit_fsub(self, lhs: str, rhs: str) -> str:
        r = self.fresh("fs")
        self._p(f"  {r} = fsub float {lhs}, {rhs}")
        return r

    def emit_fmul(self, lhs: str, rhs: str) -> str:
        r = self.fresh("fm")
        self._p(f"  {r} = fmul float {lhs}, {rhs}")
        return r

    def emit_fdiv(self, lhs: str, rhs: str) -> str:
        r = self.fresh("fd")
        self._p(f"  {r} = fdiv float {lhs}, {rhs}")
        return r

    def emit_fneg(self, src: str) -> str:
        r = self.fresh("fn")
        self._p(f"  {r} = fneg float {src}")
        return r

    def emit_fcmp(self, predicate: str, lhs: str, rhs: str) -> str:
        """Float comparison. Returns i1 SSA name."""
        r = self.fresh("fcmp")
        self._p(f"  {r} = fcmp {predicate} float {lhs}, {rhs}")
        return r

    def emit_select(self, cond: str, true_val: str, false_val: str) -> str:
        """Select between two float values based on i1 condition."""
        r = self.fresh("sel")
        self._p(f"  {r} = select i1 {cond}, float {true_val}, float {false_val}")
        return r

    # -- integer arithmetic ------------------------------------------------

    def emit_i32_const(self, value: int) -> str:
        r = self.fresh("ic")
        self._p(f"  {r} = add i32 0, {value}")
        return r

    def emit_i32_add(self, lhs: str, rhs: str) -> str:
        r = self.fresh("ia")
        self._p(f"  {r} = add i32 {lhs}, {rhs}")
        return r

    def emit_i32_sub(self, lhs: str, rhs: str) -> str:
        r = self.fresh("is")
        self._p(f"  {r} = sub i32 {lhs}, {rhs}")
        return r

    def emit_i32_mul(self, lhs: str, rhs: str) -> str:
        r = self.fresh("im")
        self._p(f"  {r} = mul i32 {lhs}, {rhs}")
        return r

    def emit_i32_sdiv(self, lhs: str, rhs: str) -> str:
        r = self.fresh("id")
        self._p(f"  {r} = sdiv i32 {lhs}, {rhs}")
        return r

    def emit_i32_rem(self, lhs: str, rhs: str) -> str:
        r = self.fresh("ir")
        self._p(f"  {r} = srem i32 {lhs}, {rhs}")
        return r

    def emit_i32_icmp(self, predicate: str, lhs: str, rhs: str) -> str:
        r = self.fresh("icmp")
        self._p(f"  {r} = icmp {predicate} i32 {lhs}, {rhs}")
        return r

    def emit_i32_and(self, lhs: str, rhs: str) -> str:
        r = self.fresh("iand")
        self._p(f"  {r} = and i32 {lhs}, {rhs}")
        return r

    # -- control flow ------------------------------------------------------

    def emit_br(self, target: str) -> None:
        self._p(f"  br label %{target}")

    def emit_br_cond(self, cond: str, true_label: str, false_label: str) -> None:
        self._p(f"  br i1 {cond}, label %{true_label}, label %{false_label}")

    def emit_ret_void(self) -> None:
        self._p("  ret void")

    def emit_ret(self, ty: str, value: str) -> None:
        self._p(f"  ret {ty} {value}")

    # -- call --------------------------------------------------------------

    def emit_call(self, ret_ty: str, fn_name: str,
                  args: list[tuple[str, str]]) -> str:
        """Call a function. Returns SSA name of the result (or empty if void).

        Args:
            ret_ty: Return type.
            fn_name: Callee name (with ``@``).
            args: List of ``(type, value)`` pairs.
        """
        arg_str = ", ".join(f"{ty} {val}" for ty, val in args)
        if ret_ty == "void":
            self._p(f"  call void {fn_name}({arg_str})")
            return ""
        else:
            r = self.fresh("call")
            self._p(f"  {r} = call {ret_ty} {fn_name}({arg_str})")
            return r

    # -- phi ---------------------------------------------------------------

    def emit_phi(self, ty: str, incoming: list[tuple[str, str]]) -> str:
        """Emit a phi node. Returns SSA name.

        Args:
            ty: Type (e.g. ``"float"`` or ``"i32"``).
            incoming: List of ``(value, label)`` pairs.
        """
        r = self.fresh("phi")
        parts = ", ".join(f"[ {val}, %{lbl} ]" for val, lbl in incoming)
        self._p(f"  {r} = phi {ty} {parts}")
        return r

    # -- output ------------------------------------------------------------

    def get_ir(self) -> str:
        return "\n".join(self._lines) + "\n"

    def save(self, path: str) -> None:
        with open(path, "w") as f:
            f.write(self.get_ir())


# ---------------------------------------------------------------------------
# Part 2: LLVMCNNGenerator — CNN operator code generation
# ---------------------------------------------------------------------------


def _prod(seq) -> int:
    """Product of an iterable of integers."""
    p = 1
    for x in seq:
        p *= x
    return p


class LLVMCNNGenerator:
    """Generates LLVM IR for CNN models with real nested-loop computation.

    Each ONNX operator becomes a separate LLVM function.  The main
    function allocates a stack workspace, copies input, calls each
    operator in topological order, and copies the final output.
    """

    def __init__(self, model: ONNXModel):
        self.model = model
        self.memory = MemoryPlan()
        self.ir = LLVMIRBuilder()
        self._op_counter = 0
        self._weight_names: dict[str, str] = {}  # tensor name -> global @ name
        self._op_fn_names: list[tuple[int, str, str]] = []  # [(idx, op_type, fn_name)]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self) -> str:
        """Generate the complete LLVM IR module as a string."""
        # Pass 1: plan workspace layout
        self._plan_workspace()
        # Pass 2: emit module
        self._emit_module_header()
        self._emit_weight_globals()
        self._emit_inline_expf()
        # Emit each operator as a separate function
        for node in self.model.nodes:
            self._emit_operator(node)
        # Emit main dispatch function
        self._emit_main_function()
        self.ir.comment("End of module")
        return self.ir.get_ir()

    # ------------------------------------------------------------------
    # Workspace planning (two-pass: first plan, then emit)
    # ------------------------------------------------------------------

    def _plan_workspace(self) -> None:
        """Reserve workspace offsets for all tensors.

        This mirrors the RISC-V pipeline's MemoryPlan usage but separates
        allocation from code emission so the main function can know the
        total workspace size upfront for its ``alloca``.
        """
        # Input tensor workspace
        if self.model.inputs:
            inp = self.model.inputs[0]
            in_shape = self.model.get_shape(inp.name)
            in_el = _prod(in_shape) if in_shape else 1
            self.memory.alloc_workspace(inp.name, in_el)

        # Each node's output
        for node in self.model.nodes:
            out_name = node.outputs[0]
            out_shape = self.model.get_shape(out_name)
            out_el = _prod(out_shape) if out_shape else 1
            self.memory.alloc_workspace(out_name, out_el)

    # ------------------------------------------------------------------
    # Module header
    # ------------------------------------------------------------------

    def _emit_module_header(self) -> None:
        self.ir.emit_module_header("riscv64-unknown-elf")

    def _emit_inline_expf(self) -> None:
        """Emit an always-inline float exp function using Taylor series.

        Uses Horner's method with 10 terms.  Accurate enough for CNN sigmoid
        when the input is clamped to ``[-10, 10]``.

        No external library calls — pure float32 arithmetic.
        """
        self.ir.emit_function_start("float", "inline_expf", [
            ("float", "%x"),
        ], linkage="internal", fn_attrs="alwaysinline")
        # Taylor series: exp(x) ≈ Σ x^k/k!   (Horner form, 10 terms)
        # Clamp x to [-20, 10] to avoid overflow / unacceptable error
        c10 = self.ir.emit_float_const(10.0)
        cm20 = self.ir.emit_float_const(-20.0)
        gt10 = self.ir.emit_fcmp("ogt", "%x", c10)
        x1 = self.ir.emit_select(gt10, c10, "%x")
        lt_m20 = self.ir.emit_fcmp("olt", x1, cm20)
        t = self.ir.emit_select(lt_m20, cm20, x1)
        # Horner series: 1 + x*(1 + x/2*(1 + x/3*(1 + ... x/9*(1 + x/10)...)))
        c1  = self.ir.emit_float_const(1.0)
        c2  = self.ir.emit_float_const(2.0)
        c3  = self.ir.emit_float_const(3.0)
        c4  = self.ir.emit_float_const(4.0)
        c5  = self.ir.emit_float_const(5.0)
        c6  = self.ir.emit_float_const(6.0)
        c7  = self.ir.emit_float_const(7.0)
        c8  = self.ir.emit_float_const(8.0)
        c9  = self.ir.emit_float_const(9.0)
        c10_2 = self.ir.emit_float_const(10.0)
        # Build from innermost: 1 + t/10
        s1  = self.ir.emit_fdiv(t, c10_2)
        s2  = self.ir.emit_fadd(c1, s1)
        # 1 + t/9 * prev
        s3  = self.ir.emit_fdiv(t, c9)
        s4  = self.ir.emit_fmul(s3, s2)
        s5  = self.ir.emit_fadd(c1, s4)
        s6  = self.ir.emit_fdiv(t, c8)
        s7  = self.ir.emit_fmul(s6, s5)
        s8  = self.ir.emit_fadd(c1, s7)
        s9  = self.ir.emit_fdiv(t, c7)
        s10 = self.ir.emit_fmul(s9, s8)
        s11 = self.ir.emit_fadd(c1, s10)
        s12 = self.ir.emit_fdiv(t, c6)
        s13 = self.ir.emit_fmul(s12, s11)
        s14 = self.ir.emit_fadd(c1, s13)
        s15 = self.ir.emit_fdiv(t, c5)
        s16 = self.ir.emit_fmul(s15, s14)
        s17 = self.ir.emit_fadd(c1, s16)
        s18 = self.ir.emit_fdiv(t, c4)
        s19 = self.ir.emit_fmul(s18, s17)
        s20 = self.ir.emit_fadd(c1, s19)
        s21 = self.ir.emit_fdiv(t, c3)
        s22 = self.ir.emit_fmul(s21, s20)
        s23 = self.ir.emit_fadd(c1, s22)
        s24 = self.ir.emit_fdiv(t, c2)
        s25 = self.ir.emit_fmul(s24, s23)
        result = self.ir.emit_fadd(c1, s25)
        self.ir.emit_ret("float", result)
        self.ir.emit_function_end()

    # ------------------------------------------------------------------
    # Weight globals
    # ------------------------------------------------------------------

    def _emit_weight_globals(self) -> None:
        for name, tensor in self.model.initializers.items():
            if tensor.data_type != ONNX_FLOAT or not tensor.data:
                continue
            # Unpack float32 bytes to Python float list
            n = len(tensor.data) // 4
            values = list(struct.unpack(f"<{n}f", tensor.data))
            safe = name.replace(".", "_").replace("/", "_")
            gname = self.ir.emit_global_float_array(safe, values)
            self._weight_names[name] = gname

    # ------------------------------------------------------------------
    # Operator dispatch
    # ------------------------------------------------------------------

    def _emit_operator(self, node: NodeInfo) -> None:
        op = node.op_type.lower()
        handler = getattr(self, f"_emit_{op}", None)
        if handler is None:
            raise ValueError(f"Unsupported op: {node.op_type} ({node.name})")
        self._op_counter += 1
        handler(node)

    def _op_fn_name(self, op_type: str) -> str:
        """Return a unique function name for an operator instance."""
        return f"{op_type.lower()}_{self._op_counter}"

    def _register_op(self, op_type: str) -> str:
        fn = self._op_fn_name(op_type)
        self._op_fn_names.append((self._op_counter, op_type, fn))
        return fn

    # ------------------------------------------------------------------
    # Workspace pointer helpers
    # ------------------------------------------------------------------

    def _ws_ptr(self, ws_alloca: str, name: str) -> str:
        """Return a float* GEP into workspace for a given tensor name."""
        off = self.memory.get_workspace_offset(name)
        assert off % 4 == 0, f"Workspace offset for {name} not float-aligned: {off}"
        idx = self.ir.emit_i32_const(off // 4)
        return self.ir.emit_gep("float", ws_alloca, idx)

    # ------------------------------------------------------------------
    # Element-wise copy loop (shared helper)
    # ------------------------------------------------------------------

    def _emit_element_copy(self, src_ptr: str, dst_ptr: str, num_elements: int) -> None:
        """Emit a loop that copies ``num_elements`` floats from src to dst."""
        if num_elements == 0:
            return
        i_ptr = self.ir.emit_alloca("i32", 1)
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), i_ptr)

        header = self.ir.fresh_block("copy_hdr")
        body = self.ir.fresh_block("copy_body")
        exit_b = self.ir.fresh_block("copy_exit")
        self.ir.emit_br(header)

        self.ir.label(header)
        i_val = self.ir.emit_load("i32", i_ptr)
        cond = self.ir.emit_i32_icmp("slt", i_val, self.ir.emit_i32_const(num_elements))
        self.ir.emit_br_cond(cond, body, exit_b)

        self.ir.label(body)
        sp = self.ir.emit_gep("float", src_ptr, i_val)
        dp = self.ir.emit_gep("float", dst_ptr, i_val)
        val = self.ir.emit_load("float", sp)
        self.ir.emit_store("float", val, dp)
        next_i = self.ir.emit_i32_add(i_val, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", next_i, i_ptr)
        self.ir.emit_br(header)

        self.ir.label(exit_b)

    # ==================================================================
    # ReLU
    # ==================================================================

    def _emit_relu(self, node: NodeInfo) -> None:
        """emit @relu_N(float* %in, float* %out, i32 %n)"""
        fn = self._register_op("relu")
        x_name, out_name = node.inputs[0], node.outputs[0]
        out_shape = self.model.get_shape(out_name)
        N = _prod(out_shape) if out_shape else 1

        self.ir.emit_function_start("void", fn, [
            ("float*", "%in"), ("float*", "%out"),
        ], linkage="internal", fn_attrs="alwaysinline")
        i_ptr = self.ir.emit_alloca("i32", 1)
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), i_ptr)

        hdr = self.ir.fresh_block("relu_hdr")
        bdy = self.ir.fresh_block("relu_body")
        ext = self.ir.fresh_block("relu_exit")
        self.ir.emit_br(hdr)

        self.ir.label(hdr)
        iv = self.ir.emit_load("i32", i_ptr)
        c = self.ir.emit_i32_icmp("slt", iv, self.ir.emit_i32_const(N))
        self.ir.emit_br_cond(c, bdy, ext)

        self.ir.label(bdy)
        ip = self.ir.emit_gep("float", "%in", iv)
        op = self.ir.emit_gep("float", "%out", iv)
        v = self.ir.emit_load("float", ip)
        z = self.ir.emit_float_const(0.0)
        gt = self.ir.emit_fcmp("ogt", v, z)
        r = self.ir.emit_select(gt, v, z)
        self.ir.emit_store("float", r, op)
        nxt = self.ir.emit_i32_add(iv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nxt, i_ptr)
        self.ir.emit_br(hdr)

        self.ir.label(ext)
        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ==================================================================
    # Reshape (element-wise copy)
    # ==================================================================

    def _emit_reshape(self, node: NodeInfo) -> None:
        """emit @reshape_N(float* %in, float* %out) — element copy."""
        fn = self._register_op("reshape")
        x_name, out_name = node.inputs[0], node.outputs[0]
        out_shape = self.model.get_shape(out_name)
        N = _prod(out_shape) if out_shape else 1

        self.ir.emit_function_start("void", fn, [
            ("float*", "%in"), ("float*", "%out"),
        ], linkage="internal", fn_attrs="alwaysinline")
        self._emit_element_copy("%in", "%out", N)
        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ==================================================================
    # Sigmoid: 1.0 / (1.0 + exp(-x))
    # ==================================================================

    def _emit_sigmoid(self, node: NodeInfo) -> None:
        """emit @sigmoid_N(float* %in, float* %out)"""
        fn = self._register_op("sigmoid")
        out_name = node.outputs[0]
        out_shape = self.model.get_shape(out_name)
        N = _prod(out_shape) if out_shape else 1

        self.ir.emit_function_start("void", fn, [
            ("float*", "%in"), ("float*", "%out"),
        ], linkage="internal", fn_attrs="alwaysinline")
        i_ptr = self.ir.emit_alloca("i32", 1)
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), i_ptr)

        hdr = self.ir.fresh_block("sig_hdr")
        bdy = self.ir.fresh_block("sig_body")
        ext = self.ir.fresh_block("sig_exit")
        self.ir.emit_br(hdr)

        self.ir.label(hdr)
        iv = self.ir.emit_load("i32", i_ptr)
        c = self.ir.emit_i32_icmp("slt", iv, self.ir.emit_i32_const(N))
        self.ir.emit_br_cond(c, bdy, ext)

        self.ir.label(bdy)
        ip = self.ir.emit_gep("float", "%in", iv)
        op = self.ir.emit_gep("float", "%out", iv)
        v = self.ir.emit_load("float", ip)
        neg = self.ir.emit_fneg(v)
        e = self.ir.emit_call("float", "@inline_expf", [("float", neg)])
        one = self.ir.emit_float_const(1.0)
        denom = self.ir.emit_fadd(one, e)
        r = self.ir.emit_fdiv(one, denom)
        self.ir.emit_store("float", r, op)
        nxt = self.ir.emit_i32_add(iv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nxt, i_ptr)
        self.ir.emit_br(hdr)

        self.ir.label(ext)
        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ==================================================================
    # Gemm: C = A @ W^T + bias  (assuming transB=1)
    # ==================================================================

    def _emit_gemm(self, node: NodeInfo) -> None:
        """emit @gemm_N(float* %A, float* %C, float* %W, float* %bias).

        Algorithm (3 nested loops):

            for i in range(M):
                for j in range(N):
                    acc = bias[j]
                    for k in range(K):
                        acc += A[i*K + k] * W[j*K + k]
                    C[i*N + j] = acc
        """
        fn = self._register_op("gemm")
        a_name, w_name, b_name = node.inputs[0], node.inputs[1], node.inputs[2]
        out_name = node.outputs[0]

        a_shape = self.model.get_shape(a_name)
        w_shape = self.model.get_shape(w_name)
        out_shape = self.model.get_shape(out_name)

        # Extract M, K, N
        M = a_shape[0] if len(a_shape) > 0 else 1
        K = a_shape[1] if len(a_shape) > 1 else 1

        trans_b = node.attrs.get("transB", 0)
        if trans_b:
            N_w = w_shape[0] if len(w_shape) > 0 else 1
            # K_w = w_shape[1] if len(w_shape) > 1 else 1
        else:
            N_w = w_shape[1] if len(w_shape) > 1 else 1
            # K_w = w_shape[0] if len(w_shape) > 0 else 1

        # For our models, trans_b is usually true and N = w_shape[0]
        if out_shape:
            M_out = out_shape[0] if len(out_shape) > 0 else 1
            N = out_shape[1] if len(out_shape) > 1 else 1
        else:
            N = N_w

        self.ir.comment(f"  Gemm: M={M} K={K} N={N} transB={trans_b}")

        self.ir.emit_function_start("void", fn, [
            ("float*", "%A"), ("float*", "%C"),
            ("float*", "%W"), ("float*", "%bias"),
        ], linkage="internal", fn_attrs="alwaysinline")

        # Loop counters on stack
        i_ptr = self.ir.emit_alloca("i32", 1)
        j_ptr = self.ir.emit_alloca("i32", 1)
        k_ptr = self.ir.emit_alloca("i32", 1)
        acc_ptr = self.ir.emit_alloca("float", 1)

        # Init i = 0
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), i_ptr)

        # --- i loop header ---
        ih = self.ir.fresh_block("gemm_i_hdr")
        ib = self.ir.fresh_block("gemm_i_body")
        ie = self.ir.fresh_block("gemm_i_exit")
        self.ir.emit_br(ih)

        self.ir.label(ih)
        iv = self.ir.emit_load("i32", i_ptr)
        ic = self.ir.emit_i32_icmp("slt", iv, self.ir.emit_i32_const(M))
        self.ir.emit_br_cond(ic, ib, ie)

        self.ir.label(ib)
        # Init j = 0
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), j_ptr)

        # --- j loop header ---
        jh = self.ir.fresh_block("gemm_j_hdr")
        jb = self.ir.fresh_block("gemm_j_body")
        je = self.ir.fresh_block("gemm_j_exit")
        self.ir.emit_br(jh)

        self.ir.label(jh)
        jv = self.ir.emit_load("i32", j_ptr)
        jc = self.ir.emit_i32_icmp("slt", jv, self.ir.emit_i32_const(N))
        self.ir.emit_br_cond(jc, jb, je)

        self.ir.label(jb)
        # acc = bias[j]
        bp = self.ir.emit_gep("float", "%bias", jv)
        bv = self.ir.emit_load("float", bp)
        self.ir.emit_store("float", bv, acc_ptr)

        # Init k = 0
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), k_ptr)

        # --- k loop header ---
        kh = self.ir.fresh_block("gemm_k_hdr")
        kb = self.ir.fresh_block("gemm_k_body")
        ke = self.ir.fresh_block("gemm_k_exit")
        self.ir.emit_br(kh)

        self.ir.label(kh)
        kv = self.ir.emit_load("i32", k_ptr)
        kc = self.ir.emit_i32_icmp("slt", kv, self.ir.emit_i32_const(K))
        self.ir.emit_br_cond(kc, kb, ke)

        self.ir.label(kb)
        # A[i, k] = A[i*K + k]
        iK = self.ir.emit_i32_mul(iv, self.ir.emit_i32_const(K))
        a_off = self.ir.emit_i32_add(iK, kv)
        ap = self.ir.emit_gep("float", "%A", a_off)
        av = self.ir.emit_load("float", ap)

        # W[j, k] = W[j*K + k] (transB=1 layout)
        jK = self.ir.emit_i32_mul(jv, self.ir.emit_i32_const(K))
        w_off_w = self.ir.emit_i32_add(jK, kv)
        wp = self.ir.emit_gep("float", "%W", w_off_w)
        wv = self.ir.emit_load("float", wp)

        # acc += A[i,k] * W[j,k]
        prod = self.ir.emit_fmul(av, wv)
        old_acc = self.ir.emit_load("float", acc_ptr)
        new_acc = self.ir.emit_fadd(old_acc, prod)
        self.ir.emit_store("float", new_acc, acc_ptr)

        # k++
        nk = self.ir.emit_i32_add(kv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nk, k_ptr)
        self.ir.emit_br(kh)

        # --- k exit: store result ---
        self.ir.label(ke)
        # C[i, j] = C[i*N + j] = acc
        iN = self.ir.emit_i32_mul(iv, self.ir.emit_i32_const(N))
        c_off = self.ir.emit_i32_add(iN, jv)
        cp = self.ir.emit_gep("float", "%C", c_off)
        facc = self.ir.emit_load("float", acc_ptr)
        self.ir.emit_store("float", facc, cp)

        # j++
        nj = self.ir.emit_i32_add(jv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nj, j_ptr)
        self.ir.emit_br(jh)

        # --- j exit ---
        self.ir.label(je)
        # i++
        ni = self.ir.emit_i32_add(iv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", ni, i_ptr)
        self.ir.emit_br(ih)

        # --- i exit ---
        self.ir.label(ie)
        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ==================================================================
    # MaxPool2D: NCHW layout, 5-deep nested loops
    # ==================================================================

    def _emit_maxpool(self, node: NodeInfo) -> None:
        """emit @maxpool2d_N(float* %in, float* %out).

        Algorithm (5 nested loops):

            for c in range(C):
                for oh in range(H_out):
                    for ow in range(W_out):
                        max_val = -3.4e38
                        for kh in range(K):
                            for kw in range(K):
                                ih = oh*S + kh
                                iw = ow*S + kw
                                val = in[c*H*W + ih*W + iw]
                                if val > max_val: max_val = val
                        out[c*H_out*W_out + oh*W_out + ow] = max_val
        """
        fn = self._register_op("maxpool")
        x_name, out_name = node.inputs[0], node.outputs[0]
        x_shape = self.model.get_shape(x_name)
        out_shape = self.model.get_shape(out_name)

        N, C, H, W = self._nchw(x_shape)
        _, _, H_out, W_out = self._nchw(out_shape)

        # Kernel and stride
        kernel_attr = node.attrs.get("kernel_shape", [2, 2])
        stride_attr = node.attrs.get("strides", [2, 2])
        if isinstance(kernel_attr, (list, tuple)):
            Kh, Kw = kernel_attr[0], kernel_attr[1] if len(kernel_attr) > 1 else kernel_attr[0]
        else:
            Kh = Kw = int(kernel_attr)
        if isinstance(stride_attr, (list, tuple)):
            Sh, Sw = stride_attr[0], stride_attr[1] if len(stride_attr) > 1 else stride_attr[0]
        else:
            Sh = Sw = int(stride_attr)

        self.ir.comment(f"  MaxPool: C={C} H={H}→{H_out} W={W}→{W_out} K={Kh}x{Kw} S={Sh}x{Sw}")

        self.ir.emit_function_start("void", fn, [
            ("float*", "%in"), ("float*", "%out"),
        ], linkage="internal", fn_attrs="alwaysinline")

        # Loop counters
        c_ptr = self.ir.emit_alloca("i32", 1)
        oh_ptr = self.ir.emit_alloca("i32", 1)
        ow_ptr = self.ir.emit_alloca("i32", 1)
        kh_ptr = self.ir.emit_alloca("i32", 1)
        kw_ptr = self.ir.emit_alloca("i32", 1)
        max_ptr = self.ir.emit_alloca("float", 1)

        HW = H * W
        HoWo = H_out * W_out

        # --- c loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), c_ptr)
        ch = self.ir.fresh_block("mp_c_hdr")
        cb = self.ir.fresh_block("mp_c_body")
        ce = self.ir.fresh_block("mp_c_exit")
        self.ir.emit_br(ch)

        self.ir.label(ch)
        cv = self.ir.emit_load("i32", c_ptr)
        cc = self.ir.emit_i32_icmp("slt", cv, self.ir.emit_i32_const(C))
        self.ir.emit_br_cond(cc, cb, ce)

        self.ir.label(cb)
        cHW = self.ir.emit_i32_mul(cv, self.ir.emit_i32_const(HW))
        cHoWo = self.ir.emit_i32_mul(cv, self.ir.emit_i32_const(HoWo))

        # --- oh loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), oh_ptr)
        ohh = self.ir.fresh_block("mp_oh_hdr")
        ohb = self.ir.fresh_block("mp_oh_body")
        ohe = self.ir.fresh_block("mp_oh_exit")
        self.ir.emit_br(ohh)

        self.ir.label(ohh)
        ohv = self.ir.emit_load("i32", oh_ptr)
        ohc = self.ir.emit_i32_icmp("slt", ohv, self.ir.emit_i32_const(H_out))
        self.ir.emit_br_cond(ohc, ohb, ohe)

        self.ir.label(ohb)
        ohW = self.ir.emit_i32_mul(ohv, self.ir.emit_i32_const(W))

        # --- ow loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), ow_ptr)
        owh = self.ir.fresh_block("mp_ow_hdr")
        owb = self.ir.fresh_block("mp_ow_body")
        owe = self.ir.fresh_block("mp_ow_exit")
        self.ir.emit_br(owh)

        self.ir.label(owh)
        owv = self.ir.emit_load("i32", ow_ptr)
        owc = self.ir.emit_i32_icmp("slt", owv, self.ir.emit_i32_const(W_out))
        self.ir.emit_br_cond(owc, owb, owe)

        self.ir.label(owb)
        # max_val = large negative (well within float32 range)
        neg_inf = self.ir.emit_float_const(-1.0e+30)
        self.ir.emit_store("float", neg_inf, max_ptr)

        # --- kh loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), kh_ptr)
        khh = self.ir.fresh_block("mp_kh_hdr")
        khb = self.ir.fresh_block("mp_kh_body")
        khe = self.ir.fresh_block("mp_kh_exit")
        self.ir.emit_br(khh)

        self.ir.label(khh)
        khv = self.ir.emit_load("i32", kh_ptr)
        khc = self.ir.emit_i32_icmp("slt", khv, self.ir.emit_i32_const(Kh))
        self.ir.emit_br_cond(khc, khb, khe)

        self.ir.label(khb)
        # ih = oh*S + kh
        ohSh = self.ir.emit_i32_mul(ohv, self.ir.emit_i32_const(Sh))
        ih = self.ir.emit_i32_add(ohSh, khv)
        ihW = self.ir.emit_i32_mul(ih, self.ir.emit_i32_const(W))

        # --- kw loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), kw_ptr)
        kwh = self.ir.fresh_block("mp_kw_hdr")
        kwb = self.ir.fresh_block("mp_kw_body")
        kwe = self.ir.fresh_block("mp_kw_exit")
        self.ir.emit_br(kwh)

        self.ir.label(kwh)
        kwv = self.ir.emit_load("i32", kw_ptr)
        kwc = self.ir.emit_i32_icmp("slt", kwv, self.ir.emit_i32_const(Kw))
        self.ir.emit_br_cond(kwc, kwb, kwe)

        self.ir.label(kwb)
        # iw = ow*S + kw
        owSw = self.ir.emit_i32_mul(owv, self.ir.emit_i32_const(Sw))
        iw = self.ir.emit_i32_add(owSw, kwv)
        # in_offset = c*H*W + ih*W + iw
        in_off = self.ir.emit_i32_add(cHW, ihW)
        in_off = self.ir.emit_i32_add(in_off, iw)
        ip = self.ir.emit_gep("float", "%in", in_off)
        val = self.ir.emit_load("float", ip)
        # max_val = val > max_val ? val : max_val
        cmpf = self.ir.emit_fcmp("ogt", val,
                                  self.ir.emit_load("float", max_ptr))
        new_m = self.ir.emit_select(cmpf, val,
                                     self.ir.emit_load("float", max_ptr))
        self.ir.emit_store("float", new_m, max_ptr)

        # kw++
        nkw = self.ir.emit_i32_add(kwv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nkw, kw_ptr)
        self.ir.emit_br(kwh)

        # --- kw exit ---
        self.ir.label(kwe)
        # kh++
        nkh = self.ir.emit_i32_add(khv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nkh, kh_ptr)
        self.ir.emit_br(khh)

        # --- kh exit: store result ---
        self.ir.label(khe)
        # out[c*H_out*W_out + oh*W_out + ow]
        out_off = self.ir.emit_i32_add(cHoWo,
                    self.ir.emit_i32_mul(ohv, self.ir.emit_i32_const(W_out)))
        out_off = self.ir.emit_i32_add(out_off, owv)
        op = self.ir.emit_gep("float", "%out", out_off)
        fm = self.ir.emit_load("float", max_ptr)
        self.ir.emit_store("float", fm, op)

        # ow++
        n_ow = self.ir.emit_i32_add(owv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", n_ow, ow_ptr)
        self.ir.emit_br(owh)

        # --- ow exit ---
        self.ir.label(owe)
        n_oh = self.ir.emit_i32_add(ohv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", n_oh, oh_ptr)
        self.ir.emit_br(ohh)

        # --- oh exit ---
        self.ir.label(ohe)
        n_c = self.ir.emit_i32_add(cv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", n_c, c_ptr)
        self.ir.emit_br(ch)

        # --- c exit ---
        self.ir.label(ce)
        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ==================================================================
    # Conv2D: NCHW, 6-deep nested loops with padding
    # ==================================================================

    def _emit_conv(self, node: NodeInfo) -> None:
        """emit @conv2d_N(float* %in, float* %out, float* %W, float* %bias).

        Algorithm (6 nested loops, NCHW):

            for oc in range(C_out):
                acc = bias[oc]
                for oh in range(H_out):
                    for ow in range(W_out):
                        for ic in range(C_in):
                            for kh in range(K):
                                for kw in range(K):
                                    ih = oh*S + kh - P
                                    iw = ow*S + kw - P
                                    if 0 <= ih < H and 0 <= iw < W:
                                        acc += in[ic*H*W + ih*W + iw]
                                             * W[oc*C_in*K*K + ic*K*K + kh*K + kw]
                        out[oc*H_out*W_out + oh*W_out + ow] = acc
        """
        fn = self._register_op("conv")
        x_name, w_name, b_name = node.inputs[0], node.inputs[1], node.inputs[2]
        out_name = node.outputs[0]

        x_shape = self.model.get_shape(x_name)
        w_shape = self.model.get_shape(w_name)
        out_shape = self.model.get_shape(out_name)

        N, C_in, H, W = self._nchw(x_shape)
        C_out = w_shape[0] if len(w_shape) > 0 else 1
        K = w_shape[2] if len(w_shape) > 2 else 3

        _, _, H_out, W_out = self._nchw(out_shape)

        # Strides and padding
        stride_attr = node.attrs.get("strides", [1, 1])
        pad_attr = node.attrs.get("pads", [0, 0, 0, 0])
        if isinstance(stride_attr, (list, tuple)):
            Sh, Sw = stride_attr[0], stride_attr[1] if len(stride_attr) > 1 else stride_attr[0]
        else:
            Sh = Sw = int(stride_attr)
        if isinstance(pad_attr, (list, tuple)) and len(pad_attr) >= 4:
            ph, pw = pad_attr[0], pad_attr[2]
        elif isinstance(pad_attr, (list, tuple)):
            ph = pw = pad_attr[0]
        else:
            ph = pw = int(pad_attr)

        self.ir.comment(
            f"  Conv2D: C_in={C_in} C_out={C_out} H={H}→{H_out} W={W}→{W_out} "
            f"K={K} S={Sh}x{Sw} P={ph}x{pw}"
        )

        self.ir.emit_function_start("void", fn, [
            ("float*", "%in"), ("float*", "%out"),
            ("float*", "%W"), ("float*", "%bias"),
        ], linkage="internal", fn_attrs="alwaysinline")

        # Loop counters (6 counters)
        oc_ptr = self.ir.emit_alloca("i32", 1)
        oh_ptr = self.ir.emit_alloca("i32", 1)
        ow_ptr = self.ir.emit_alloca("i32", 1)
        ic_ptr = self.ir.emit_alloca("i32", 1)
        kh_ptr = self.ir.emit_alloca("i32", 1)
        kw_ptr = self.ir.emit_alloca("i32", 1)
        acc_ptr = self.ir.emit_alloca("float", 1)

        HW = H * W
        HoWo = H_out * W_out
        CinKK = C_in * K * K
        KK = K * K

        # --- oc loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), oc_ptr)
        och = self.ir.fresh_block("conv_oc_hdr")
        ocb = self.ir.fresh_block("conv_oc_body")
        oce = self.ir.fresh_block("conv_oc_exit")
        self.ir.emit_br(och)

        self.ir.label(och)
        ocv = self.ir.emit_load("i32", oc_ptr)
        occ = self.ir.emit_i32_icmp("slt", ocv, self.ir.emit_i32_const(C_out))
        self.ir.emit_br_cond(occ, ocb, oce)

        self.ir.label(ocb)
        # Precompute weight base for this output channel
        oc_CinKK = self.ir.emit_i32_mul(ocv, self.ir.emit_i32_const(CinKK))
        oc_HoWo = self.ir.emit_i32_mul(ocv, self.ir.emit_i32_const(HoWo))

        # --- oh loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), oh_ptr)
        ohh = self.ir.fresh_block("conv_oh_hdr")
        ohb = self.ir.fresh_block("conv_oh_body")
        ohe = self.ir.fresh_block("conv_oh_exit")
        self.ir.emit_br(ohh)

        self.ir.label(ohh)
        ohv = self.ir.emit_load("i32", oh_ptr)
        ohc = self.ir.emit_i32_icmp("slt", ohv, self.ir.emit_i32_const(H_out))
        self.ir.emit_br_cond(ohc, ohb, ohe)

        self.ir.label(ohb)
        # ih_start = oh * stride - pad  (for bounds check, but we check per-element)
        ohSh = self.ir.emit_i32_mul(ohv, self.ir.emit_i32_const(Sh))

        # --- ow loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), ow_ptr)
        owh = self.ir.fresh_block("conv_ow_hdr")
        owb = self.ir.fresh_block("conv_ow_body")
        owe = self.ir.fresh_block("conv_ow_exit")
        self.ir.emit_br(owh)

        self.ir.label(owh)
        owv = self.ir.emit_load("i32", ow_ptr)
        owc = self.ir.emit_i32_icmp("slt", owv, self.ir.emit_i32_const(W_out))
        self.ir.emit_br_cond(owc, owb, owe)

        self.ir.label(owb)
        # Load bias[oc] into acc
        bp = self.ir.emit_gep("float", "%bias", ocv)
        bv = self.ir.emit_load("float", bp)
        self.ir.emit_store("float", bv, acc_ptr)

        owSw = self.ir.emit_i32_mul(owv, self.ir.emit_i32_const(Sw))

        # --- ic loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), ic_ptr)
        ich = self.ir.fresh_block("conv_ic_hdr")
        icb = self.ir.fresh_block("conv_ic_body")
        ice = self.ir.fresh_block("conv_ic_exit")
        self.ir.emit_br(ich)

        self.ir.label(ich)
        icv = self.ir.emit_load("i32", ic_ptr)
        icc = self.ir.emit_i32_icmp("slt", icv, self.ir.emit_i32_const(C_in))
        self.ir.emit_br_cond(icc, icb, ice)

        self.ir.label(icb)
        # Input base = ic*H*W
        ic_HW = self.ir.emit_i32_mul(icv, self.ir.emit_i32_const(HW))
        # Weight base for this ic: oc*C_in*K*K + ic*K*K
        ic_KK = self.ir.emit_i32_mul(icv, self.ir.emit_i32_const(KK))
        w_ocic = self.ir.emit_i32_add(oc_CinKK, ic_KK)

        # --- kh loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), kh_ptr)
        khh = self.ir.fresh_block("conv_kh_hdr")
        khb = self.ir.fresh_block("conv_kh_body")
        khe = self.ir.fresh_block("conv_kh_exit")
        self.ir.emit_br(khh)

        self.ir.label(khh)
        khv = self.ir.emit_load("i32", kh_ptr)
        khc = self.ir.emit_i32_icmp("slt", khv, self.ir.emit_i32_const(K))
        self.ir.emit_br_cond(khc, khb, khe)

        self.ir.label(khb)
        # ih = oh*S + kh - P
        ohS_kh = self.ir.emit_i32_add(ohSh, khv)
        ih_val = self.ir.emit_i32_sub(ohS_kh, self.ir.emit_i32_const(ph))
        # Bounds check for H: ih >= 0 and ih < H
        ih_ge0 = self.ir.emit_i32_icmp("sge", ih_val, self.ir.emit_i32_const(0))
        ih_ltH = self.ir.emit_i32_icmp("slt", ih_val, self.ir.emit_i32_const(H))
        ih_ok = self.ir.emit_i32_and(ih_ge0, ih_ltH)
        ihW = self.ir.emit_i32_mul(ih_val, self.ir.emit_i32_const(W))
        in_base = self.ir.emit_i32_add(ic_HW, ihW)
        # Weight: kh*K
        kh_K = self.ir.emit_i32_mul(khv, self.ir.emit_i32_const(K))
        w_base = self.ir.emit_i32_add(w_ocic, kh_K)

        # --- kw loop ---
        self.ir.emit_store("i32", self.ir.emit_i32_const(0), kw_ptr)
        kwh = self.ir.fresh_block("conv_kw_hdr")
        kwb = self.ir.fresh_block("conv_kw_body")
        kwe = self.ir.fresh_block("conv_kw_exit")
        self.ir.emit_br(kwh)

        self.ir.label(kwh)
        kwv = self.ir.emit_load("i32", kw_ptr)
        kwc = self.ir.emit_i32_icmp("slt", kwv, self.ir.emit_i32_const(K))
        self.ir.emit_br_cond(kwc, kwb, kwe)

        self.ir.label(kwb)
        # iw = ow*S + kw - P
        owS_kw = self.ir.emit_i32_add(owSw, kwv)
        iw_val = self.ir.emit_i32_sub(owS_kw, self.ir.emit_i32_const(pw))
        # Bounds check for W: iw >= 0 and iw < W
        iw_ge0 = self.ir.emit_i32_icmp("sge", iw_val, self.ir.emit_i32_const(0))
        iw_ltW = self.ir.emit_i32_icmp("slt", iw_val, self.ir.emit_i32_const(W))
        iw_ok = self.ir.emit_i32_and(iw_ge0, iw_ltW)
        bounds_ok = self.ir.emit_i32_and(ih_ok, iw_ok)

        # If bounds ok, do MAC
        mac_body = self.ir.fresh_block("conv_mac")
        mac_skip = self.ir.fresh_block("conv_skip")
        self.ir.emit_br_cond(bounds_ok, mac_body, mac_skip)

        self.ir.label(mac_body)
        # Input[in_base + iw]
        inp_off = self.ir.emit_i32_add(in_base, iw_val)
        ip = self.ir.emit_gep("float", "%in", inp_off)
        iv = self.ir.emit_load("float", ip)
        # Weight[w_base + kw]
        w_off = self.ir.emit_i32_add(w_base, kwv)
        wp = self.ir.emit_gep("float", "%W", w_off)
        wv = self.ir.emit_load("float", wp)
        # acc += iv * wv
        prod = self.ir.emit_fmul(iv, wv)
        old_a = self.ir.emit_load("float", acc_ptr)
        new_a = self.ir.emit_fadd(old_a, prod)
        self.ir.emit_store("float", new_a, acc_ptr)
        self.ir.emit_br(mac_skip)

        self.ir.label(mac_skip)
        # kw++
        nkw = self.ir.emit_i32_add(kwv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nkw, kw_ptr)
        self.ir.emit_br(kwh)

        # --- kw exit ---
        self.ir.label(kwe)
        # kh++
        nkh = self.ir.emit_i32_add(khv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nkh, kh_ptr)
        self.ir.emit_br(khh)

        # --- kh exit ---
        self.ir.label(khe)
        # ic++
        nic = self.ir.emit_i32_add(icv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", nic, ic_ptr)
        self.ir.emit_br(ich)

        # --- ic exit: store result ---
        self.ir.label(ice)
        # out[oc*H_out*W_out + oh*W_out + ow]
        ohWo = self.ir.emit_i32_mul(ohv, self.ir.emit_i32_const(W_out))
        out_off = self.ir.emit_i32_add(oc_HoWo, ohWo)
        out_off = self.ir.emit_i32_add(out_off, owv)
        op = self.ir.emit_gep("float", "%out", out_off)
        fa = self.ir.emit_load("float", acc_ptr)
        self.ir.emit_store("float", fa, op)

        # ow++
        n_ow = self.ir.emit_i32_add(owv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", n_ow, ow_ptr)
        self.ir.emit_br(owh)

        # --- ow exit ---
        self.ir.label(owe)
        n_oh = self.ir.emit_i32_add(ohv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", n_oh, oh_ptr)
        self.ir.emit_br(ohh)

        # --- oh exit ---
        self.ir.label(ohe)
        n_oc = self.ir.emit_i32_add(ocv, self.ir.emit_i32_const(1))
        self.ir.emit_store("i32", n_oc, oc_ptr)
        self.ir.emit_br(och)

        # --- oc exit ---
        self.ir.label(oce)
        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ==================================================================
    # Main dispatch function
    # ==================================================================

    def _emit_main_function(self) -> None:
        """Emit @main_graph(float* %input, float* %output).

        Allocates workspace on the stack, copies input, calls each operator
        in topological order, and copies the final output.
        """
        total_ws = self.memory.workspace_size // 4  # number of floats
        self.ir.comment(f"Workspace: {total_ws} floats ({self.memory.workspace_size} bytes)")

        self.ir.emit_function_start("void", "main_graph", [
            ("float*", "%input"), ("float*", "%output"),
        ])

        # For large workspaces, use comment about malloc (avoid stack overflow in JIT)
        # The alloca approach works for LLVM IR but may overflow stack at runtime.
        # Production code should call @malloc for workspaces > a few MB.
        ws = self.ir.emit_alloca("float", max(total_ws, 1))
        if total_ws * 4 > 1024 * 1024:
            self.ir.comment(
                f"  WARNING: workspace is {total_ws * 4 / (1024*1024):.1f} MB. "
                f"Consider using malloc() instead of alloca() for production use."
            )

        # Copy input tensor to workspace
        if self.model.inputs:
            inp = self.model.inputs[0]
            in_shape = self.model.get_shape(inp.name)
            in_el = _prod(in_shape) if in_shape else 1
            if in_el > 0:
                in_ptr = self._ws_ptr(ws, inp.name)
                self.ir.comment(f"Copy input: {inp.name} ({in_el} elements)")
                self._emit_element_copy("%input", in_ptr, in_el)

        # Call each operator
        for idx, op_type, fn_name in self._op_fn_names:
            node = self.model.nodes[idx - 1]  # idx is 1-based
            out_name = node.outputs[0]
            out_shape = self.model.get_shape(out_name)
            out_el = _prod(out_shape) if out_shape else 1

            self.ir.comment(f"Op [{idx}] {op_type}: {node.name}")

            if op_type == "relu":
                x_ptr = self._ws_ptr(ws, node.inputs[0])
                o_ptr = self._ws_ptr(ws, out_name)
                self.ir.emit_call("void", f"@{fn_name}", [
                    ("float*", x_ptr), ("float*", o_ptr),
                ])

            elif op_type == "reshape":
                x_ptr = self._ws_ptr(ws, node.inputs[0])
                o_ptr = self._ws_ptr(ws, out_name)
                self.ir.emit_call("void", f"@{fn_name}", [
                    ("float*", x_ptr), ("float*", o_ptr),
                ])

            elif op_type == "sigmoid":
                x_ptr = self._ws_ptr(ws, node.inputs[0])
                o_ptr = self._ws_ptr(ws, out_name)
                self.ir.emit_call("void", f"@{fn_name}", [
                    ("float*", x_ptr), ("float*", o_ptr),
                ])

            elif op_type == "maxpool":
                x_ptr = self._ws_ptr(ws, node.inputs[0])
                o_ptr = self._ws_ptr(ws, out_name)
                self.ir.emit_call("void", f"@{fn_name}", [
                    ("float*", x_ptr), ("float*", o_ptr),
                ])

            elif op_type == "gemm":
                a_ptr = self._ws_ptr(ws, node.inputs[0])
                c_ptr = self._ws_ptr(ws, out_name)
                w_g = self._weight_names[node.inputs[1]]
                b_g = self._weight_names[node.inputs[2]]
                # Get float* from global arrays
                w_size = _prod(self.model.get_shape(node.inputs[1]))
                b_size = _prod(self.model.get_shape(node.inputs[2]))
                w_ptr = self._global_array_ptr(w_g, w_size)
                b_ptr = self._global_array_ptr(b_g, b_size)
                self.ir.emit_call("void", f"@{fn_name}", [
                    ("float*", a_ptr), ("float*", c_ptr),
                    ("float*", w_ptr), ("float*", b_ptr),
                ])

            elif op_type == "conv":
                x_ptr = self._ws_ptr(ws, node.inputs[0])
                o_ptr = self._ws_ptr(ws, out_name)
                w_g = self._weight_names[node.inputs[1]]
                b_g = self._weight_names[node.inputs[2]]
                w_size = _prod(self.model.get_shape(node.inputs[1]))
                b_size = _prod(self.model.get_shape(node.inputs[2]))
                w_ptr = self._global_array_ptr(w_g, w_size)
                b_ptr = self._global_array_ptr(b_g, b_size)
                self.ir.emit_call("void", f"@{fn_name}", [
                    ("float*", x_ptr), ("float*", o_ptr),
                    ("float*", w_ptr), ("float*", b_ptr),
                ])

            else:
                self.ir.comment(f"  ; SKIP unsupported: {op_type}")

        # Copy final output from workspace to %output
        if self.model.outputs:
            outp = self.model.outputs[0]
            out_shape = self.model.get_shape(outp.name)
            out_el = _prod(out_shape) if out_shape else 1
            if out_el > 0:
                o_ptr = self._ws_ptr(ws, outp.name)
                self.ir.comment(f"Copy output: {outp.name} ({out_el} elements)")
                self._emit_element_copy(o_ptr, "%output", out_el)

        self.ir.emit_ret_void()
        self.ir.emit_function_end()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _nchw(shape: tuple) -> tuple:
        """Unpack shape to (N, C, H, W), filling missing dims with 1."""
        s = list(shape) if shape else []
        while len(s) < 4:
            s.insert(0 if len(s) <= 2 else 1, 1)
        # Ensure we have N, C, H, W order
        return (s[0], s[1], s[2], s[3])

    def _global_array_ptr(self, gname: str, num_elements: int) -> str:
        """Return a float* GEP pointing to the first element of a global array.

        For ``@w = constant [N x float] [...]``, need:
        ``getelementptr [N x float], [N x float]* @w, i32 0, i32 0``
        which yields a ``float*``.
        """
        array_ty = f"[{num_elements} x float]"
        return self.ir.emit_gep_raw(array_ty, gname, ["i32 0", "i32 0"])


# ---------------------------------------------------------------------------
# Part 3: LLVMJITRunner — JIT execution via libLLVM (optional)
# ---------------------------------------------------------------------------


class LLVMJITRunner:
    """JIT-compile and run LLVM IR using libLLVM.so via ctypes.

    Uses the LLVM-C API for parsing IR, creating an execution engine,
    and calling the compiled ``main_graph`` function.

    Falls back to a Python reference interpreter if the LLVM library
    cannot be loaded.
    """

    def __init__(self, llvm_ir: str):
        self._ir = llvm_ir
        self._lib = None
        self._engine = None
        self._module = None
        self._context = None

    def _load_libllvm(self) -> ctypes.CDLL:
        """Load libLLVM shared library."""
        if self._lib is not None:
            return self._lib

        candidates = [
            "libLLVM-20.so",
            "libLLVM.so.20.1",
            "libLLVM.so.20",
            "libLLVM.so",
        ]
        for name in candidates:
            try:
                self._lib = ctypes.CDLL(name)
                return self._lib
            except OSError:
                continue
        raise RuntimeError(
            "Cannot load libLLVM.  Install llvm-20 or set LD_LIBRARY_PATH."
        )

    def compile(self) -> None:
        """Parse LLVM IR and create a JIT execution engine."""
        lib = self._load_libllvm()

        # -- Type definitions for LLVM-C API --
        # Opaque pointer types
        LLVMModuleRef = ctypes.c_void_p
        LLVMContextRef = ctypes.c_void_p
        LLVMExecutionEngineRef = ctypes.c_void_p
        LLVMMemoryBufferRef = ctypes.c_void_p
        LLVMValueRef = ctypes.c_void_p

        c_char_p = ctypes.c_char_p
        c_size_t = ctypes.c_size_t

        # LLVMContextCreate()
        lib.LLVMContextCreate.restype = LLVMContextRef
        lib.LLVMContextCreate.argtypes = []

        # LLVMCreateMemoryBufferWithMemoryRange(InputData, InputDataLength, BufferName, RequiresNullTerminator)
        lib.LLVMCreateMemoryBufferWithMemoryRange.restype = ctypes.c_bool
        lib.LLVMCreateMemoryBufferWithMemoryRange.argtypes = [
            c_char_p, c_size_t, c_char_p, ctypes.c_bool,
        ]

        # LLVMParseIRInContext(ContextRef, MemBuf, OutModule, OutMessage)
        lib.LLVMParseIRInContext.restype = ctypes.c_bool
        lib.LLVMParseIRInContext.argtypes = [
            LLVMContextRef, LLVMMemoryBufferRef,
            ctypes.POINTER(LLVMModuleRef),
            ctypes.POINTER(c_char_p),
        ]

        # LLVMCreateExecutionEngineForModule(OutEE, M, OutError)
        lib.LLVMCreateExecutionEngineForModule.restype = ctypes.c_bool
        lib.LLVMCreateExecutionEngineForModule.argtypes = [
            ctypes.POINTER(LLVMExecutionEngineRef),
            LLVMModuleRef,
            ctypes.POINTER(c_char_p),
        ]

        # LLVMGetFunctionAddress(EE, Name)
        lib.LLVMGetFunctionAddress.restype = ctypes.c_uint64
        lib.LLVMGetFunctionAddress.argtypes = [LLVMExecutionEngineRef, c_char_p]

        # LLVMDisposeModule(M)
        lib.LLVMDisposeModule.restype = None
        lib.LLVMDisposeModule.argtypes = [LLVMModuleRef]

        # LLVMDisposeExecutionEngine(EE)
        lib.LLVMDisposeExecutionEngine.restype = None
        lib.LLVMDisposeExecutionEngine.argtypes = [LLVMExecutionEngineRef]

        # LLVMContextDispose(C)
        lib.LLVMContextDispose.restype = None
        lib.LLVMContextDispose.argtypes = [LLVMContextRef]

        try:
            self._context = lib.LLVMContextCreate()
            ir_bytes = self._ir.encode("utf-8")

            mem_buf = LLVMMemoryBufferRef()
            ok = lib.LLVMCreateMemoryBufferWithMemoryRange(
                ir_bytes, len(ir_bytes), b"scratchv_module", False,
            )
            if not ok:
                raise RuntimeError("Failed to create LLVM memory buffer from IR")

            out_module = LLVMModuleRef()
            out_msg = c_char_p()
            ok = lib.LLVMParseIRInContext(
                self._context, mem_buf,
                ctypes.byref(out_module), ctypes.byref(out_msg),
            )
            if not ok:
                err = out_msg.value.decode() if out_msg.value else "unknown error"
                raise RuntimeError(f"LLVM IR parse error: {err}")

            self._module = out_module

            engine = LLVMExecutionEngineRef()
            err_msg_ee = c_char_p()
            ok = lib.LLVMCreateExecutionEngineForModule(
                ctypes.byref(engine), self._module,
                ctypes.byref(err_msg_ee),
            )
            if not ok:
                err = err_msg_ee.value.decode() if err_msg_ee.value else "unknown error"
                raise RuntimeError(f"Failed to create LLVM execution engine: {err}")

            self._engine = engine

        except Exception as e:
            self.dispose()
            raise e

    def run(self, input_data: bytes, output_size: int) -> bytes:
        """Run the compiled ``main_graph`` function.

        Args:
            input_data: Raw float32 bytes for the input tensor.
            output_size: Number of floats expected in output.

        Returns:
            Raw float32 bytes of the output tensor.
        """
        if self._engine is None:
            raise RuntimeError("Not compiled. Call compile() first.")

        lib = self._load_libllvm()
        func_addr = lib.LLVMGetFunctionAddress(self._engine, b"main_graph")
        if func_addr == 0:
            raise RuntimeError(
                "Function 'main_graph' not found in compiled module."
            )

        # Prepare input and output buffers as ctypes arrays
        in_floats = len(input_data) // 4
        out_bytes = output_size * 4

        in_buf = (ctypes.c_float * in_floats).from_buffer_copy(input_data)
        out_buf = (ctypes.c_float * output_size)()

        # Cast function pointer
        FUNC_TYPE = ctypes.CFUNCTYPE(
            None,
            ctypes.POINTER(ctypes.c_float),  # input
            ctypes.POINTER(ctypes.c_float),  # output
        )
        fn = FUNC_TYPE(func_addr)

        fn(in_buf, out_buf)

        return bytes(out_buf)

    def dispose(self) -> None:
        """Release LLVM resources."""
        lib = self._lib
        if lib is None:
            return
        if self._engine is not None:
            lib.LLVMDisposeExecutionEngine(self._engine)
            self._engine = None
        if self._module is not None:
            lib.LLVMDisposeModule(self._module)
            self._module = None
        if self._context is not None:
            lib.LLVMContextDispose(self._context)
            self._context = None


# ---------------------------------------------------------------------------
# Part 4: CLI and main pipeline
# ---------------------------------------------------------------------------


def convert_onnx_to_llvm(model_path: str) -> str:
    """Parse an ONNX model and return its LLVM IR text.

    This is the top-level pipeline function, analogous to
    ``convert_onnx_to_riscv()`` in the RISC-V standalone.
    """
    model = ONNXModel.from_file(model_path)
    generator = LLVMCNNGenerator(model)
    return generator.generate()


def _estimate_static_instructions(llvm_ir: str) -> dict:
    """Count static LLVM IR instructions for rough comparison.

    Returns a dict with counts of different instruction types.
    """
    counts = {
        "total_lines": 0,
        "fadd": 0, "fsub": 0, "fmul": 0, "fdiv": 0, "fneg": 0,
        "load": 0, "store": 0, "alloca": 0, "gep": 0,
        "br": 0, "br_cond": 0, "ret": 0, "call": 0,
        "fcmp": 0, "select": 0, "icmp": 0,
        "add_i32": 0, "mul_i32": 0, "sub_i32": 0,
        "and": 0, "phi": 0,
        "functions": 0,
    }
    for line in llvm_ir.split("\n"):
        stripped = line.strip()
        counts["total_lines"] += 1
        if stripped.startswith("define "):
            counts["functions"] += 1
        if "= fadd " in stripped:
            counts["fadd"] += 1
        elif "= fsub " in stripped:
            counts["fsub"] += 1
        elif "= fmul " in stripped:
            counts["fmul"] += 1
        elif "= fdiv " in stripped:
            counts["fdiv"] += 1
        elif "= fneg " in stripped:
            counts["fneg"] += 1
        elif "= load " in stripped:
            counts["load"] += 1
        elif "store " in stripped:
            counts["store"] += 1
        elif "= alloca " in stripped:
            counts["alloca"] += 1
        elif "= getelementptr " in stripped:
            counts["gep"] += 1
        elif stripped.startswith("br label "):
            counts["br"] += 1
        elif stripped.startswith("br i1 "):
            counts["br_cond"] += 1
        elif stripped.startswith("ret "):
            counts["ret"] += 1
        elif "= call " in stripped or stripped.startswith("call "):
            counts["call"] += 1
        elif "= fcmp " in stripped:
            counts["fcmp"] += 1
        elif "= select " in stripped:
            counts["select"] += 1
        elif "= icmp " in stripped:
            counts["icmp"] += 1
        elif "= add i32 " in stripped:
            counts["add_i32"] += 1
        elif "= mul i32 " in stripped:
            counts["mul_i32"] += 1
        elif "= sub i32 " in stripped:
            counts["sub_i32"] += 1
        elif "= and i1 " in stripped:
            counts["and"] += 1
        elif "= phi " in stripped:
            counts["phi"] += 1
    return counts


def _compute_dynamic_ops(model: ONNXModel) -> dict:
    """Estimate dynamic compute operations for the CNN model.

    WARNING: This is an analytical estimate, not actual execution.
    It computes the total number of inner-loop MAC operations and
    output stores for each layer, matching the structure of the
    generated LLVM IR.
    """
    total_fadd = 0  # float additions (bias add, acc add, etc.)
    total_fmul = 0  # float multiplications
    total_mem = 0   # float loads + stores

    for node in model.nodes:
        op = node.op_type.lower()
        if op == "conv":
            x_name, w_name = node.inputs[0], node.inputs[1]
            out_name = node.outputs[0]
            _, C_in, _, _ = LLVMCNNGenerator._nchw(model.get_shape(x_name))
            w_shape = model.get_shape(w_name)
            C_out = w_shape[0]
            K = w_shape[2] if len(w_shape) > 2 else 3
            _, _, H_out, W_out = LLVMCNNGenerator._nchw(model.get_shape(out_name))

            # Inner loop iterations
            inner = C_out * H_out * W_out * C_in * K * K
            total_fmul += inner  # one fmul per MAC
            total_fadd += inner + C_out * H_out * W_out  # fadd + bias add
            total_mem += inner * 2 + C_out * H_out * W_out  # load in + load w + store out

        elif op == "gemm":
            a_shape = model.get_shape(node.inputs[0])
            out_shape = model.get_shape(node.outputs[0])
            M = a_shape[0] if a_shape else 1
            K = a_shape[1] if len(a_shape) > 1 else 1
            N = out_shape[1] if len(out_shape) > 1 else 1

            inner = M * N * K
            total_fmul += inner
            total_fadd += inner + M * N  # MAC + bias
            total_mem += inner * 2 + M * N  # load A + load W + store C

        elif op == "maxpool":
            out_shape = model.get_shape(node.outputs[0])
            _, C, H_out, W_out = LLVMCNNGenerator._nchw(out_shape)
            K = node.attrs.get("kernel_shape", [2, 2])
            Kh, Kw = (K[0], K[1]) if isinstance(K, (list, tuple)) else (K, K)
            total_mem += C * H_out * W_out * Kh * Kw  # input loads
            total_mem += C * H_out * W_out  # output stores

        elif op == "relu" or op == "sigmoid":
            out_shape = model.get_shape(node.outputs[0])
            N = _prod(out_shape) if out_shape else 1
            total_mem += N * 2  # load + store

        elif op == "reshape":
            out_shape = model.get_shape(node.outputs[0])
            N = _prod(out_shape) if out_shape else 1
            total_mem += N * 2  # load + store

    # Each float op in LLVM is 1 instruction; mem ops are load + store + gep
    # For the JIT (native x86), each LLVM IR op typically becomes 1-2 x86 instrs
    return {
        "float_ops": total_fadd + total_fmul,
        "fadd": total_fadd,
        "fmul": total_fmul,
        "mem_ops": total_mem,
        "approx_total": total_fadd + total_fmul + total_mem,
    }


def _do_compile_riscv(llvm_ir: str, output_path: str, static: dict, dyn: dict,
                      opt_level: int = 2) -> None:
    """Compile LLVM IR to RISC-V assembly via libLLVM and print comparison."""
    import ctypes

    print("\n[2/3] Compiling LLVM IR → RISC-V assembly via libLLVM...")
    try:
        lib = ctypes.CDLL("libLLVM-20.so")
    except OSError:
        print("  ERROR: libLLVM-20.so not found. Install llvm-20 package.")
        return

    c_char_p = ctypes.c_char_p; c_size_t = ctypes.c_size_t
    ir_bytes = llvm_ir.encode("utf-8")

    # Context + parse
    lib.LLVMContextCreate.restype = ctypes.c_void_p; lib.LLVMContextCreate.argtypes = []
    ctx = lib.LLVMContextCreate()

    lib.LLVMCreateMemoryBufferWithMemoryRange.restype = ctypes.c_void_p
    lib.LLVMCreateMemoryBufferWithMemoryRange.argtypes = [c_char_p, c_size_t, c_char_p, ctypes.c_bool]
    buf = lib.LLVMCreateMemoryBufferWithMemoryRange(ir_bytes, len(ir_bytes), b"scratchv", False)

    lib.LLVMParseIRInContext.restype = ctypes.c_int
    lib.LLVMParseIRInContext.argtypes = [ctypes.c_void_p, ctypes.c_void_p,
        ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(c_char_p)]
    mod = ctypes.c_void_p(); err = c_char_p()
    rc = lib.LLVMParseIRInContext(ctx, buf, ctypes.byref(mod), ctypes.byref(err))
    if rc != 0:
        em = err.value.decode() if err.value else "unknown"
        print(f"  PARSE ERROR: {em[:200]}")
        lib.LLVMContextDispose(ctx)
        return
    print("  Parse OK")

    # Run always-inline pass to flatten all operator functions
    lib.LLVMCreatePassBuilderOptions.restype = ctypes.c_void_p
    lib.LLVMCreatePassBuilderOptions.argtypes = []
    pb_opts = lib.LLVMCreatePassBuilderOptions()

    lib.LLVMRunPasses.restype = ctypes.c_void_p  # LLVMErrorRef
    lib.LLVMRunPasses.argtypes = [ctypes.c_void_p, ctypes.c_char_p,
                                   ctypes.c_void_p, ctypes.c_void_p]
    # Step 1: always-inline → flatten all @alwaysinline functions into main_graph
    err_pb = lib.LLVMRunPasses(mod, b"always-inline", ctypes.c_void_p(0), pb_opts)
    if err_pb:
        print("  Warning: always-inline pass returned error (continuing)")
    else:
        print("  Inline pass OK")
    # Step 2: globaldce → remove now-unused function definitions
    err_pb2 = lib.LLVMRunPasses(mod, b"globaldce", ctypes.c_void_p(0), pb_opts)
    if err_pb2:
        print("  Warning: globaldce pass returned error (continuing)")
    else:
        print("  DCE pass OK — dead functions removed")

    lib.LLVMDisposePassBuilderOptions.restype = None
    lib.LLVMDisposePassBuilderOptions.argtypes = [ctypes.c_void_p]
    lib.LLVMDisposePassBuilderOptions(pb_opts)

    # Init RISC-V target
    lib.LLVMInitializeRISCVTargetInfo(); lib.LLVMInitializeRISCVTarget()
    lib.LLVMInitializeRISCVTargetMC(); lib.LLVMInitializeRISCVAsmPrinter()

    lib.LLVMGetTargetFromTriple.restype = ctypes.c_int
    lib.LLVMGetTargetFromTriple.argtypes = [c_char_p, ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(c_char_p)]
    target = ctypes.c_void_p()
    lib.LLVMGetTargetFromTriple(b"riscv64-unknown-elf", ctypes.byref(target), ctypes.byref(ctypes.c_char_p()))

    def _compile(features, label):
        lib.LLVMCreateTargetMachine.restype = ctypes.c_void_p
        lib.LLVMCreateTargetMachine.argtypes = [ctypes.c_void_p, c_char_p, c_char_p, c_char_p,
            ctypes.c_int, ctypes.c_int, ctypes.c_int]
        tm = lib.LLVMCreateTargetMachine(target, b"riscv64-unknown-elf", b"generic-rv64",
            features.encode(), ctypes.c_int(opt_level), ctypes.c_int(0), ctypes.c_int(0))

        lib.LLVMTargetMachineEmitToMemoryBuffer.restype = ctypes.c_int
        lib.LLVMTargetMachineEmitToMemoryBuffer.argtypes = [ctypes.c_void_p, ctypes.c_void_p,
            ctypes.c_int, ctypes.POINTER(c_char_p), ctypes.POINTER(ctypes.c_void_p)]
        eerr = c_char_p(); out_buf = ctypes.c_void_p()
        rc = lib.LLVMTargetMachineEmitToMemoryBuffer(tm, mod, ctypes.c_int(0),
            ctypes.byref(eerr), ctypes.byref(out_buf))
        if rc != 0:
            emsg = eerr.value.decode() if eerr.value else "unknown"
            print(f"  EMIT ERROR ({label}): {emsg[:200]}")
            lib.LLVMDisposeTargetMachine(tm)
            return 0

        lib.LLVMGetBufferStart.restype = c_char_p; lib.LLVMGetBufferStart.argtypes = [ctypes.c_void_p]
        lib.LLVMGetBufferSize.restype = c_size_t; lib.LLVMGetBufferSize.argtypes = [ctypes.c_void_p]
        ptr = lib.LLVMGetBufferStart(out_buf); size = lib.LLVMGetBufferSize(out_buf)
        asm = ctypes.string_at(ptr, size).decode("utf-8", errors="replace")

        asm_path = output_path.replace(".ll", f"_{label}_O{opt_level}.s")
        with open(asm_path, "w") as f:
            f.write(asm)

        # Count instructions
        code_count = 0; cats = {}
        for l in asm.split("\n"):
            s = l.strip()
            if not s: continue
            if s.startswith(".") or s.endswith(":") or s.startswith("//"): continue
            parts = s.split("#")[0].strip()
            if parts and not parts.startswith("."):
                op = parts.split()[0]; cats[op] = cats.get(op, 0) + 1; code_count += 1

        lib.LLVMDisposeTargetMachine(tm)
        return code_count, cats, asm_path

    # Compile with both configs (+m avoids __muldi3 library calls)
    print("  Compiling RV64IM (soft-float + M)...")
    rv64im_count, rv64im_cats, rv64im_path = _compile("+m", "rv64im")
    print(f"    → {rv64im_count:,} instructions → {rv64im_path}")

    print("  Compiling RV64IMAFD (HW float + M)...")
    rv64fd_count, rv64fd_cats, rv64fd_path = _compile("+m,+f,+d", "rv64fd")
    print(f"    → {rv64fd_count:,} instructions → {rv64fd_path}")

    lib.LLVMContextDispose(ctx)

    # Compare with benchmark
    from scratchv.standalone.benchmark import estimate_cnn_model
    bench = estimate_cnn_model()
    rv_bench_static = 785
    rv_bench_dynamic = bench["total_estimated"]

    print(f"\n{'='*70}")
    print(f"  LLVM (真实嵌套循环) → RISC-V vs ScratchV RISC-V codegen")
    print(f"  LLVM 20.1 llc | riscv64-unknown-elf")
    print(f"{'='*70}")
    print(f"  {'配置':<30} {'静态指令':>10} {'vs ScratchV':>12} {'估算动态':>15}")
    print(f"  {'-'*30} {'-'*10} {'-'*12} {'-'*15}")
    for label, count in [("LLVM→RV64IM (soft-float)", rv64im_count),
                          ("LLVM→RV64IMAFD (HW float)", rv64fd_count),
                          ("ScratchV RISC-V (Q16.16)", rv_bench_static)]:
        ratio = count / rv_bench_static if count > 0 else 0
        est_dyn = int(count / rv_bench_static * rv_bench_dynamic) if count > 0 else 0
        print(f"  {label:<30} {count:>10,} {ratio:>11.1f}x {est_dyn:>14,}")
    print()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="ScratchV: Library-free ONNX → LLVM IR CNN code generator"
    )
    parser.add_argument("model", help="Path to ONNX model file (.onnx)")
    parser.add_argument("-o", "--output", default="output.ll",
                        help="Output LLVM IR file (default: output.ll)")
    parser.add_argument("--run", action="store_true",
                        help="JIT-compile and run to measure performance")
    parser.add_argument("--compare", action="store_true",
                        help="Compare against standalone RISC-V benchmark")
    parser.add_argument("--compile-riscv", action="store_true",
                        help="Use libLLVM to compile LLVM IR to RISC-V assembly and compare")
    parser.add_argument("--opt-level", type=int, default=2, choices=[0, 1, 2, 3],
                        help="LLVM optimization level: 0=None 1=Less 2=Default 3=Aggressive (default: 2)")
    parser.add_argument("--opt-levels", type=str, default=None,
                        help="Comma-separated list of opt levels to test, e.g. '0,1,2,3'"
                             " (overrides --opt-level, produces side-by-side comparison)")
    args = parser.parse_args()

    print("ScratchV: Library-free ONNX → LLVM IR Pipeline")
    print("=" * 60)
    print(f"  Input:  {args.model}")

    # Step 1: Parse ONNX model (reuses standalone pipeline)
    model = ONNXModel.from_file(args.model)
    print(f"  Graph: {model.graph_name}")
    print(f"  Nodes: {len(model.nodes)}")
    print(f"  Initializers: {len(model.initializers)}")
    for i, node in enumerate(model.nodes):
        out_s = model.get_shape(node.outputs[0]) if node.outputs else "?"
        print(f"    [{i}] {node.op_type} → shape={out_s}")

    # Step 2: Generate LLVM IR with real nested-loop computation
    print("\n[1/3] Generating LLVM IR with real nested-loop compute...")
    generator = LLVMCNNGenerator(model)
    llvm_ir = generator.generate()

    # Step 3: Write output
    with open(args.output, "w") as f:
        f.write(llvm_ir)
    print(f"  LLVM IR written to: {args.output}")
    print(f"  Lines: {len(llvm_ir.splitlines())}")

    # Static instruction counts
    static = _estimate_static_instructions(llvm_ir)
    total_static = sum(v for k, v in static.items()
                       if k not in ("total_lines", "functions"))
    print(f"  Static LLVM IR instructions: {total_static}")
    print(f"  Functions: {static['functions']}")
    print(f"  - fadd: {static['fadd']}, fmul: {static['fmul']}, fdiv: {static['fdiv']}")
    print(f"  - load: {static['load']}, store: {static['store']}, alloca: {static['alloca']}")
    print(f"  - br: {static['br']}, br_cond: {static['br_cond']}, icmp: {static['icmp']}")
    print(f"  - gep: {static['gep']}, call: {static['call']}")
    print(f"  - fcmp: {static['fcmp']}, select: {static['select']}")
    print(f"  - i32 math: {static['add_i32'] + static['mul_i32'] + static['sub_i32']} (add={static['add_i32']} mul={static['mul_i32']} sub={static['sub_i32']})")

    # Analytical dynamic op estimation
    dyn = _compute_dynamic_ops(model)
    print(f"\n  Analytical dynamic operation estimate (inner loops):")
    print(f"  - Float compute ops:  {dyn['float_ops']:>15,} (fadd={dyn['fadd']:,} fmul={dyn['fmul']:,})")
    print(f"  - Memory ops:         {dyn['mem_ops']:>15,} (loads + stores)")
    print(f"  - Approx total LLVM:  {dyn['approx_total']:>15,} dynamic ops")

    # Step 4: Optional JIT execution
    if args.run:
        print("\n[2/3] JIT compiling with libLLVM...")
        try:
            runner = LLVMJITRunner(llvm_ir)
            runner.compile()
            print("  JIT compilation OK.")

            # Prepare random input
            inp = model.inputs[0]
            in_shape = model.get_shape(inp.name)
            in_el = 1
            for d in in_shape:
                in_el *= d
            import random
            random.seed(42)
            in_bytes = b"".join(
                struct.pack("<f", random.uniform(-1.0, 1.0))
                for _ in range(in_el)
            )

            # Determine output size
            outp = model.outputs[0]
            out_shape = model.get_shape(outp.name)
            out_el = 1
            for d in out_shape:
                out_el *= d

            # Warmup
            print(f"  Running warmup (input: {in_el} floats, output: {out_el} floats)...")
            runner.run(in_bytes, out_el)

            # Timed runs
            print("  Running timed iterations...")
            times = []
            for i in range(5):
                t0 = time.perf_counter()
                runner.run(in_bytes, out_el)
                elapsed = time.perf_counter() - t0
                times.append(elapsed)
                print(f"    Run {i+1}: {elapsed*1000:.2f} ms")

            avg = sum(times) / len(times)
            print(f"\n  Average: {avg*1000:.2f} ms per inference")

            runner.dispose()
        except Exception as e:
            print(f"  JIT execution failed: {e}")
            print("  (This is expected if libLLVM.so is not loadable.)")

    # Step 5: Optional RISC-V compilation via libLLVM
    if args.compile_riscv:
        _do_compile_riscv(llvm_ir, args.output, static, dyn, opt_level=args.opt_level)

    # Step 6: Optional analytical comparison
    if args.compare:
        print("\n[3/3] Performance comparison: LLVM vs Standalone RISC-V")
        print("-" * 60)
        # Run the standalone benchmark
        from scratchv.standalone.benchmark import estimate_cnn_model
        riscv_result = estimate_cnn_model()

        riscv_instr = riscv_result.get("total_estimated", 0)
        riscv_compute = riscv_result.get("total_compute", 0)
        riscv_memory = riscv_result.get("total_memory", 0)
        riscv_time_100mhz = riscv_result.get("est_hw_time_100mhz", 0)

        print(f"  RISC-V Standalone (Q16.16 fixed-point):")
        print(f"    Total dynamic instructions:  {riscv_instr:>15,}")
        print(f"    Compute instructions:        {riscv_compute:>15,}")
        print(f"    Memory instructions:         {riscv_memory:>15,}")
        print(f"    Est. time @100MHz:           {riscv_time_100mhz:.1f}s")
        print()
        print(f"  LLVM IR (float32):")
        print(f"    Static LLVM instructions:    {total_static:>15,}")
        print(f"    Est. dynamic float ops:      {dyn['float_ops']:>15,}")
        print(f"    Est. dynamic mem ops:        {dyn['mem_ops']:>15,}")
        print(f"    Est. dynamic total:          {dyn['approx_total']:>15,}")
        print()
        if riscv_instr > 0:
            ratio = dyn['approx_total'] / riscv_instr
            print(f"  Dynamic op ratio (LLVM-float / RISC-V-Q16.16): {ratio:.2f}x")
            print(f"  RISC-V: 1 instruction = 1 operation (Q16.16 multiply = 1 RV32IM MUL)")
            print(f"  LLVM:   1 instruction = 1 float32 operation (native x86)")
            print(f"  ---")
            print(f"  Key insight: RISC-V executes {riscv_instr:,} instructions")
            print(f"  to do the same work as ~{dyn['float_ops']:,} float ops.")
            print(f"  At 100MHz RISC-V: ~{riscv_time_100mhz:.1f}s per inference")
            if dyn['float_ops'] > 0:
                est_x86_time = dyn['float_ops'] / 5e9  # assume 5 GFLOPS
                speedup = riscv_time_100mhz / est_x86_time if est_x86_time > 0 else float('inf')
                print(f"  At 5 GFLOPS x86:  ~{est_x86_time*1000:.1f}ms per inference")
                print(f"  Speedup (x86 @5GFLOPS vs RISC-V @100MHz): ~{speedup:.0f}x")

    print("\n" + "=" * 60)
    print("  Pipeline complete!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
